import os
from dotenv import load_dotenv

load_dotenv()

TOKEN = os.getenv("TOKEN")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

   8214877974,
]

GROUP_ID = -1004494734091

PAGE_SIZE = 10

(
    MEDIA_TYPE,
    CATEGORY1,
    CATEGORY2,
    TITLE,
    PRICE,
    MEDIA,
    THUMBNAIL,
    BROWSE,
    SEARCH_TITLE,
    ADD_CATEGORY,
    DELETE_CATEGORY,
    ADD_REGION,
    DELETE_REGION,
    SELECT_PARENT_CATEGORY,
    ADD_SUBCATEGORY,
    SELECT_DELETE_PARENT,
    DELETE_SUBCATEGORY,
    CHANGE_PRICE,
) = range(18)